/** @type {import('tailwindcss').Config} */
const radixColors = require('@radix-ui/colors');

module.exports = {
  darkMode: 'class',
  content: ["./src/**/*.{html,js,jsx,ts,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      colors: {
        // https://www.radix-ui.com/colors/docs/palette-composition/scales
        ...radixColors.amber,
        ...radixColors.blackA,
        ...radixColors.blue,
        ...radixColors.blueDark,
        ...radixColors.bronze,
        ...radixColors.bronzeDark,
        ...radixColors.brown,
        ...radixColors.brownDark,
        ...radixColors.crimson,
        ...radixColors.crimsonDark,
        ...radixColors.cyan,
        ...radixColors.cyanDark,
        ...radixColors.gold,
        ...radixColors.goldDark,
        ...radixColors.grass,
        ...radixColors.grassDark,
        ...radixColors.gray,
        ...radixColors.grayDark,
        ...radixColors.green,
        ...radixColors.greenDark,
        ...radixColors.indigo,
        ...radixColors.indigoDark,
        ...radixColors.lime,
        ...radixColors.limeDark,
        ...radixColors.mauve,
        ...radixColors.mauveDark,
        ...radixColors.mint,
        ...radixColors.mintDark,
        ...radixColors.olive,
        ...radixColors.oliveDark,
        ...radixColors.orange,
        ...radixColors.orangeDark,
        ...radixColors.pink,
        ...radixColors.pinkDark,
        ...radixColors.plum,
        ...radixColors.plumDark,
        ...radixColors.purple,
        ...radixColors.purpleDark,
        ...radixColors.red,
        ...radixColors.redDark,
        ...radixColors.sage,
        ...radixColors.sageDark,
        ...radixColors.sand,
        ...radixColors.sandDark,
        ...radixColors.sky,
        ...radixColors.skyDark,
        ...radixColors.slate,
        ...radixColors.slateDark,
        ...radixColors.teal,
        ...radixColors.tealDark,
        ...radixColors.tomato,
        ...radixColors.tomatoDark,
        ...radixColors.violet,
        ...radixColors.violetDark,
        ...radixColors.whiteA,
        ...radixColors.yellow,
        ...radixColors.yellowDark,
      },
    },
  },
  plugins: [require('daisyui')],
  daisyui: {
    themes: true,
  }
}