services:
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=jerneif
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
  
  seq:
    image: datalust/seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - '5341:80'
    volumes:
      - seq_data:/data
    restart: unless-stopped
      
  mailhog:
    image: mailhog/mailhog
    ports:
      - '1025:1025' # SMTP port
      - '8025:8025' # HTTP port (web ui)
    restart: always
    

volumes:
  postgres_data:
  seq_data: