export const AppRoutes = {
    NotFound: "*",
    Forbidden: "/forbidden",
    Home: "/",
    Login: "/login",
    Forgot: "/forgot",
    Rules: "/rules",
    Game: "/game",
    MyTransactions: '/transactions',
    AdminTransactions: '/admin/transactions',
    AdminUsers: '/admin/users',
    AdminUser: '/admin/user',
    MyBalanceHistory: '/balance-history',
    AdminBalanceHistory: '/admin/balance-history',
    AdminUserBalanceHistory: '/admin/balance-history/:userId',
    PickWinnerSequence: '/admin/winner-sequence',
    BoardHistory: '/board/history',
    Profile: '/me',
} as const;