name: Deploy client
on:
  push:
    branches:
      - master
    paths:
      - 'client/**'
      - '.github/workflows/firebase-client-deployment.yml'
      
jobs:
  build_and_deploy:
    name: Deploy to Firebase Hosting
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install dependencies & build
        run: cd client && npm ci && npm run build
      
      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JERNE_IF_CLIENT }}
          channelId: live
          projectId: jerne-if-client
          entryPoint: client