name: Deploy client to Firebase
on:
  push:
    paths:
      - 'client/**'
      - '.github/workflows/firebase-client-deployment.yml'
      
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v4
      - run: cd client && npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JERNE_IF_CLIENT }}
          channelId: live
          projectId: jerne-if-client
          entryPoint: client