name: Deploy server to Fly
on:
  push: 
    paths:
      - 'server/**'
      - '.github/workflows/fly-server-deployment.yml'
      - 'Directory.Build.props'
      - 'fly.toml'

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
    name: Deploy to Fly.io
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy
        run: flyctl deploy --remote-only