name: Server Tests
on:
  push:
    paths:
      - 'server/**'
      - '.github/workflows/server-tests.yml'
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: ["master"]
    paths:
      - 'server/**'
      - '.github/workflows/server-tests.yml'
  
jobs:
  server_test_job:
    name: Server test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
          
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --no-restore
        
      - name: Test
        run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" --logger "html;LogFileName=test-results.html"
      
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: '**/TestResults/*.html'
          retention-days: 7
          
      - name: Generate coverage report
        uses: danielpalme/ReportGenerator-GitHub-Action@5.4.1
        if: success()
        with:
          reports: '**/TestResults/**/coverage.cobertura.xml'
          targetdir: 'coveragereport'
          reporttypes: 'HtmlInline;Cobertura'
        
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: coverage-report
          path: coveragereport
          retention-days: 7 
